using com.celigo.net.ServiceManager.SuiteTalk;
//~ Generated by INetSuiteServiceTemplate.tt
#pragma warning disable 1591

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public interface INetSuiteService
	{
		INetSuiteService Clone();
		
		// Properties

		com.celigo.net.ServiceManager.SuiteTalk.ApplicationInfo applicationInfo { get; set; }
		com.celigo.net.ServiceManager.SuiteTalk.PartnerInfo partnerInfo { get; set; }
		com.celigo.net.ServiceManager.SuiteTalk.Passport passport { get; set; }
		com.celigo.net.ServiceManager.SuiteTalk.Preferences preferences { get; set; }
		com.celigo.net.ServiceManager.SuiteTalk.DocumentInfo documentInfo { get; set; }
		com.celigo.net.ServiceManager.SuiteTalk.SearchPreferences searchPreferences { get; set; }
		System.String Url { get; set; }
		System.Boolean UseDefaultCredentials { get; set; }
		System.Web.Services.Protocols.SoapProtocolVersion SoapVersion { get; set; }
		System.Boolean AllowAutoRedirect { get; set; }
		System.Net.CookieContainer CookieContainer { get; set; }
		System.Security.Cryptography.X509Certificates.X509CertificateCollection ClientCertificates { get; }
		System.Boolean EnableDecompression { get; set; }
		System.String UserAgent { get; set; }
		System.Net.IWebProxy Proxy { get; set; }
		System.Boolean UnsafeAuthenticatedConnectionSharing { get; set; }
		System.Net.ICredentials Credentials { get; set; }
		System.String ConnectionGroupName { get; set; }
		System.Boolean PreAuthenticate { get; set; }
		System.Text.Encoding RequestEncoding { get; set; }
		System.Int32 Timeout { get; set; }
		System.ComponentModel.ISite Site { get; set; }
		System.ComponentModel.IContainer Container { get; }
		
		// Web Service methods

		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse[] updateInviteeStatusList(com.celigo.net.ServiceManager.SuiteTalk.UpdateInviteeStatusReference[] updateInviteeStatusReference);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncAddList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncUpdateList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncUpsertList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncDeleteList(com.celigo.net.ServiceManager.SuiteTalk.BaseRef[] baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncGetList(com.celigo.net.ServiceManager.SuiteTalk.BaseRef[] baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncInitializeList(com.celigo.net.ServiceManager.SuiteTalk.InitializeRecord[] initializeRecord);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult asyncSearch(com.celigo.net.ServiceManager.SuiteTalk.SearchRecord searchRecord);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncResult getAsyncResult(System.String jobId, System.Int32 pageIndex);
		com.celigo.net.ServiceManager.SuiteTalk.AsyncStatusResult checkAsyncStatus(System.String jobId);
		com.celigo.net.ServiceManager.SuiteTalk.GetDeletedResult getDeleted(com.celigo.net.ServiceManager.SuiteTalk.GetDeletedFilter getDeletedFilter);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse[] deleteList(com.celigo.net.ServiceManager.SuiteTalk.BaseRef[] baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse[] updateList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse[] upsertList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
		com.celigo.net.ServiceManager.SuiteTalk.ReadResponse get(com.celigo.net.ServiceManager.SuiteTalk.BaseRef baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.ReadResponse[] getList(com.celigo.net.ServiceManager.SuiteTalk.BaseRef[] baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.GetAllResult getAll(com.celigo.net.ServiceManager.SuiteTalk.GetAllRecord record);
		com.celigo.net.ServiceManager.SuiteTalk.GetSavedSearchResult getSavedSearch(com.celigo.net.ServiceManager.SuiteTalk.GetSavedSearchRecord record);
		com.celigo.net.ServiceManager.SuiteTalk.GetCustomizationIdResult getCustomizationId(com.celigo.net.ServiceManager.SuiteTalk.CustomizationType customizationType, System.Boolean includeInactives);
		com.celigo.net.ServiceManager.SuiteTalk.ReadResponse initialize(com.celigo.net.ServiceManager.SuiteTalk.InitializeRecord initializeRecord);
		com.celigo.net.ServiceManager.SuiteTalk.ReadResponse[] initializeList(com.celigo.net.ServiceManager.SuiteTalk.InitializeRecord[] initializeRecord);
		com.celigo.net.ServiceManager.SuiteTalk.GetSelectValueResult getSelectValue(com.celigo.net.ServiceManager.SuiteTalk.GetSelectValueFieldDescription fieldDescription, System.Int32 pageIndex);
		com.celigo.net.ServiceManager.SuiteTalk.GetItemAvailabilityResult getItemAvailability(com.celigo.net.ServiceManager.SuiteTalk.ItemAvailabilityFilter itemAvailabilityFilter);
		com.celigo.net.ServiceManager.SuiteTalk.GetBudgetExchangeRateResult getBudgetExchangeRate(com.celigo.net.ServiceManager.SuiteTalk.BudgetExchangeRateFilter budgetExchangeRateFilter);
		com.celigo.net.ServiceManager.SuiteTalk.GetConsolidatedExchangeRateResult getConsolidatedExchangeRate(com.celigo.net.ServiceManager.SuiteTalk.ConsolidatedExchangeRateFilter consolidatedExchangeRateFilter);
		com.celigo.net.ServiceManager.SuiteTalk.GetCurrencyRateResult getCurrencyRate(com.celigo.net.ServiceManager.SuiteTalk.CurrencyRateFilter currencyRateFilter);
		com.celigo.net.ServiceManager.SuiteTalk.GetDataCenterUrlsResult getDataCenterUrls(System.String account);
		com.celigo.net.ServiceManager.SuiteTalk.GetPostingTransactionSummaryResult getPostingTransactionSummary(com.celigo.net.ServiceManager.SuiteTalk.PostingTransactionSummaryField fields, com.celigo.net.ServiceManager.SuiteTalk.PostingTransactionSummaryFilter filters, System.Int32 pageIndex);
		com.celigo.net.ServiceManager.SuiteTalk.GetServerTimeResult getServerTime();
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse attach(com.celigo.net.ServiceManager.SuiteTalk.AttachReference attachReference);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse detach(com.celigo.net.ServiceManager.SuiteTalk.DetachReference detachReference);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse updateInviteeStatus(com.celigo.net.ServiceManager.SuiteTalk.UpdateInviteeStatusReference updateInviteeStatusReference);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse login(com.celigo.net.ServiceManager.SuiteTalk.Passport passport);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse ssoLogin(com.celigo.net.ServiceManager.SuiteTalk.SsoPassport ssoPassport);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse mapSso(com.celigo.net.ServiceManager.SuiteTalk.SsoCredentials ssoCredentials);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse changePassword(com.celigo.net.ServiceManager.SuiteTalk.ChangePassword changePassword1);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse changeEmail(com.celigo.net.ServiceManager.SuiteTalk.ChangeEmail changeEmail1);
		com.celigo.net.ServiceManager.SuiteTalk.SessionResponse logout();
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse add(com.celigo.net.ServiceManager.SuiteTalk.Record record);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse delete(com.celigo.net.ServiceManager.SuiteTalk.BaseRef baseRef);
		com.celigo.net.ServiceManager.SuiteTalk.SearchResult search(com.celigo.net.ServiceManager.SuiteTalk.SearchRecord searchRecord);
		com.celigo.net.ServiceManager.SuiteTalk.SearchResult searchMore(System.Int32 pageIndex);
		com.celigo.net.ServiceManager.SuiteTalk.SearchResult searchMoreWithId(System.String searchId, System.Int32 pageIndex);
		com.celigo.net.ServiceManager.SuiteTalk.SearchResult searchNext();
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse update(com.celigo.net.ServiceManager.SuiteTalk.Record record);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse upsert(com.celigo.net.ServiceManager.SuiteTalk.Record record);
		com.celigo.net.ServiceManager.SuiteTalk.WriteResponse[] addList(com.celigo.net.ServiceManager.SuiteTalk.Record[] record);
	}
	
	public partial class NetSuiteService : INetSuiteService
	{
		public INetSuiteService Clone()
		{
			return new NetSuiteService();
		}
	}
}
