//~ Generated by RecordTemplate.tt
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class InventoryDetail	{
		/// <summary>
		/// Gets the Internal ID.
		/// </summary>
		/// <returns>The Internal ID of the record.</returns>
		public override string GetInternalId()
		{
			#warning "InventoryDetail does not support Internal IDs."
			throw new InvalidOperationException("InventoryDetail does not support Internal IDs.");
		}

		/// <summary>
		/// Sets the Internal ID.
		/// </summary>
		/// <param name="id">The Internal ID.</param>
		public override void SetInternalId(string id)
		{
			#warning "InventoryDetail does not support Internal IDs."
			throw new InvalidOperationException("InventoryDetail does not support Internal IDs.");
		}
			
	}
}
