//~ Generated by SearchRowBasicTemplate.tt
#if !FIRSTBUILD

#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class NoteTypeSearchRowBasic : ISearchRowBasic
	{
	}
}
#endif
