//~ Generated by SearchRowBasicTemplate.tt
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class PaymentMethodSearchRowBasic : ISearchRowBasic
	{
	}
}
