//~ Generated by ISupportSearchValueNTemplate.tt
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class SearchLongField 
		: ISupportSearchValue< Int64? >,  
		  ISupportSearchOperator< com.celigo.net.ServiceManager.SuiteTalk.SearchLongFieldOperator >, 
		  ISupportSearchValue2< Int64? >,
		  IBasicSearchField 
	{ 
		public Int64? GetSearchValue()
		{
			if (!this.searchValueFieldSpecified)
			{
				return null;
			}
			return this.searchValue;
		}
		
				
		public void SetSearchValue(Int64? value)
		{
			this.searchValue = value.GetValueOrDefault();
			this.searchValueSpecified = (null != value && value.HasValue); 			
		}
		
				
		public Int64? GetSearchValue2()
		{
			if (!this.searchValue2FieldSpecified)
			{
				return null;
			}
			return this.searchValue2;
		}
		
		public void SetSearchValue2(Int64? value)
		{
			this.searchValue2 = value.GetValueOrDefault();
			this.searchValue2Specified = (null != value && value.HasValue);			
		}		
	}
}

