//~ Generated by ISupportSearchValueNTemplate.tt
#if !FIRSTBUILD
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class SearchMultiSelectCustomField 
		: ISupportSearchValue< ListOrRecordRef[] > ,  
			ISupportSearchOperator< com.celigo.net.ServiceManager.SuiteTalk.SearchMultiSelectFieldOperator > 
	{ 
		public ListOrRecordRef[] GetSearchValue()
		{
			return this.searchValue;
		}
		
				
		public void SetSearchValue(ListOrRecordRef[] value)
		{
			this.searchValue = value; 			
		}
		
				
	}
}
#endif
