//~ Generated by ISupportSearchValueNTemplate.tt
#if !FIRSTBUILD
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class SearchStringField 
		: ISupportSearchValue< String > ,  
			ISupportSearchOperator< com.celigo.net.ServiceManager.SuiteTalk.SearchStringFieldOperator > 
	{ 
		public String GetSearchValue()
		{
			return this.searchValue;
		}
		
				
		public void SetSearchValue(String value)
		{
			this.searchValue = value; 			
		}
		
				
	}
}
#endif
