//~ Generated by ISupportSearchValueNTemplate.tt
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class SearchDoubleCustomField 
		: ISupportSearchValue< Double? >,  
		  ISupportSearchOperator< com.celigo.net.ServiceManager.SuiteTalk.SearchDoubleFieldOperator >, 
		  ISupportSearchValue2< Double? >,
		  IBasicSearchField 
	{ 
		public Double? GetSearchValue()
		{
			if (!this.searchValueFieldSpecified)
			{
				return null;
			}
			return this.searchValue;
		}
		
				
		public void SetSearchValue(Double? value)
		{
			this.searchValue = value.GetValueOrDefault();
			this.searchValueSpecified = (null != value && value.HasValue); 			
		}
		
				
		public Double? GetSearchValue2()
		{
			if (!this.searchValue2FieldSpecified)
			{
				return null;
			}
			return this.searchValue2;
		}
		
		public void SetSearchValue2(Double? value)
		{
			this.searchValue2 = value.GetValueOrDefault();
			this.searchValue2Specified = (null != value && value.HasValue);			
		}		
	}
}

