//~ Generated by ISupportSearchValueNTemplate.tt
#if !FIRSTBUILD
#pragma warning disable 1591
using System;

namespace com.celigo.net.ServiceManager.SuiteTalk
{
	public partial class SearchEnumMultiSelectCustomField 
		: ISupportSearchValue< String[] > ,  
			ISupportSearchOperator< com.celigo.net.ServiceManager.SuiteTalk.SearchEnumMultiSelectFieldOperator > 
	{ 
		public String[] GetSearchValue()
		{
			return this.searchValue;
		}
		
				
		public void SetSearchValue(String[] value)
		{
			this.searchValue = value; 			
		}
		
				
	}
}
#endif
