//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.8745
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 
namespace com.celigo.net.ServiceManager.SuiteTalk {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:types.sales_2015_1.transactions.webservices.netsuite.com")]
    [System.Xml.Serialization.XmlRootAttribute("celigoTransactionStatus", Namespace="urn:types.missing_2015_1.transactions.webservices.netsuite.com", IsNullable=false)]
    public enum TransactionStatus {
        
        /// <remarks/>
        _billCancelled,
        
        /// <remarks/>
        _billOpen,
        
        /// <remarks/>
        _billPaidInFull,
        
        /// <remarks/>
        _billPaymentOnlineBillPayPendingAccountingApproval,
        
        /// <remarks/>
        _billPaymentVoided,
        
        /// <remarks/>
        _billPendingApproval,
        
        /// <remarks/>
        _billRejected,
        
        /// <remarks/>
        _cashSaleDeposited,
        
        /// <remarks/>
        _cashSaleNotDeposited,
        
        /// <remarks/>
        _cashSaleUnapprovedPayment,
        
        /// <remarks/>
        _checkOnlineBillPayPendingAccountingApproval,
        
        /// <remarks/>
        _checkVoided,
        
        /// <remarks/>
        _commissionOverpaid,
        
        /// <remarks/>
        _commissionPaidInFull,
        
        /// <remarks/>
        _commissionPendingAccountingApproval,
        
        /// <remarks/>
        _commissionPendingPayment,
        
        /// <remarks/>
        _commissionRejectedByAccounting,
        
        /// <remarks/>
        _creditMemoFullyApplied,
        
        /// <remarks/>
        _creditMemoOpen,
        
        /// <remarks/>
        _customerDepositDeposited,
        
        /// <remarks/>
        _customerDepositFullyApplied,
        
        /// <remarks/>
        _customerDepositNotDeposited,
        
        /// <remarks/>
        _customerRefundVoided,
        
        /// <remarks/>
        _estimateClosed,
        
        /// <remarks/>
        _estimateExpired,
        
        /// <remarks/>
        _estimateOpen,
        
        /// <remarks/>
        _estimateProcessed,
        
        /// <remarks/>
        _estimateVoided,
        
        /// <remarks/>
        _expenseReportApprovedByAccounting,
        
        /// <remarks/>
        _expenseReportApprovedOverriddenByAccounting,
        
        /// <remarks/>
        _expenseReportInProgress,
        
        /// <remarks/>
        _expenseReportPaidInFull,
        
        /// <remarks/>
        _expenseReportPendingAccountingApproval,
        
        /// <remarks/>
        _expenseReportPendingSupervisorApproval,
        
        /// <remarks/>
        _expenseReportRejectedByAccounting,
        
        /// <remarks/>
        _expenseReportRejectedBySupervisor,
        
        /// <remarks/>
        _expenseReportRejectedOverriddenByAccounting,
        
        /// <remarks/>
        _invoiceOpen,
        
        /// <remarks/>
        _invoicePaidInFull,
        
        /// <remarks/>
        _invoicePendingApproval,
        
        /// <remarks/>
        _invoiceRejected,
        
        /// <remarks/>
        _itemFulfillmentPacked,
        
        /// <remarks/>
        _itemFulfillmentPicked,
        
        /// <remarks/>
        _itemFulfillmentShipped,
        
        /// <remarks/>
        _journalApprovedForPosting,
        
        /// <remarks/>
        _journalPendingApproval,
        
        /// <remarks/>
        _opportunityClosedLost,
        
        /// <remarks/>
        _opportunityClosedWon,
        
        /// <remarks/>
        _opportunityInProgress,
        
        /// <remarks/>
        _opportunityIssuedEstimate,
        
        /// <remarks/>
        _paycheckCommitted,
        
        /// <remarks/>
        _paycheckCreated,
        
        /// <remarks/>
        _paycheckError,
        
        /// <remarks/>
        _paycheckPendingCommitment,
        
        /// <remarks/>
        _paycheckPendingTaxCalculation,
        
        /// <remarks/>
        _paycheckPreview,
        
        /// <remarks/>
        _paycheckReversed,
        
        /// <remarks/>
        _paymentDeposited,
        
        /// <remarks/>
        _paymentNotDeposited,
        
        /// <remarks/>
        _paymentUnapprovedPayment,
        
        /// <remarks/>
        _payrollLiabilityCheckVoided,
        
        /// <remarks/>
        _purchaseOrderClosed,
        
        /// <remarks/>
        _purchaseOrderFullyBilled,
        
        /// <remarks/>
        _purchaseOrderPartiallyReceived,
        
        /// <remarks/>
        _purchaseOrderPendingBill,
        
        /// <remarks/>
        _purchaseOrderPendingBillingPartiallyReceived,
        
        /// <remarks/>
        _purchaseOrderPendingReceipt,
        
        /// <remarks/>
        _purchaseOrderPendingSupervisorApproval,
        
        /// <remarks/>
        _purchaseOrderRejectedBySupervisor,
        
        /// <remarks/>
        _requisitionCancelled,
        
        /// <remarks/>
        _requisitionClosed,
        
        /// <remarks/>
        _requisitionFullyOrdered,
        
        /// <remarks/>
        _requisitionFullyReceived,
        
        /// <remarks/>
        _requisitionPartiallyOrdered,
        
        /// <remarks/>
        _requisitionPartiallyReceived,
        
        /// <remarks/>
        _requisitionPendingApproval,
        
        /// <remarks/>
        _requisitionPendingOrder,
        
        /// <remarks/>
        _requisitionRejected,
        
        /// <remarks/>
        _returnAuthorizationCancelled,
        
        /// <remarks/>
        _returnAuthorizationClosed,
        
        /// <remarks/>
        _returnAuthorizationPartiallyReceived,
        
        /// <remarks/>
        _returnAuthorizationPendingApproval,
        
        /// <remarks/>
        _returnAuthorizationPendingReceipt,
        
        /// <remarks/>
        _returnAuthorizationPendingRefund,
        
        /// <remarks/>
        _returnAuthorizationPendingRefundPartiallyReceived,
        
        /// <remarks/>
        _returnAuthorizationRefunded,
        
        /// <remarks/>
        _salesOrderBilled,
        
        /// <remarks/>
        _salesOrderCancelled,
        
        /// <remarks/>
        _salesOrderClosed,
        
        /// <remarks/>
        _salesOrderPartiallyFulfilled,
        
        /// <remarks/>
        _salesOrderPendingApproval,
        
        /// <remarks/>
        _salesOrderPendingBilling,
        
        /// <remarks/>
        _salesOrderPendingBillingPartiallyFulfilled,
        
        /// <remarks/>
        _salesOrderPendingFulfillment,
        
        /// <remarks/>
        _salesTaxPaymentOnlineBillPayPendingAccountingApproval,
        
        /// <remarks/>
        _salesTaxPaymentVoided,
        
        /// <remarks/>
        _statementChargeOpen,
        
        /// <remarks/>
        _statementChargePaidInFull,
        
        /// <remarks/>
        _taxLiabilityChequeVoided,
        
        /// <remarks/>
        _tegataPayableEndorsed,
        
        /// <remarks/>
        _tegataPayableIssued,
        
        /// <remarks/>
        _tegataPayablePaid,
        
        /// <remarks/>
        _tegataReceivablesCollected,
        
        /// <remarks/>
        _tegataReceivablesDiscounted,
        
        /// <remarks/>
        _tegataReceivablesEndorsed,
        
        /// <remarks/>
        _tegataReceivablesHolding,
        
        /// <remarks/>
        _transferOrderClosed,
        
        /// <remarks/>
        _transferOrderPartiallyFulfilled,
        
        /// <remarks/>
        _transferOrderPendingApproval,
        
        /// <remarks/>
        _transferOrderPendingFulfillment,
        
        /// <remarks/>
        _transferOrderPendingReceipt,
        
        /// <remarks/>
        _transferOrderPendingReceiptPartiallyFulfilled,
        
        /// <remarks/>
        _transferOrderReceived,
        
        /// <remarks/>
        _transferOrderRejected,
        
        /// <remarks/>
        _vendorReturnAuthorizationCancelled,
        
        /// <remarks/>
        _vendorReturnAuthorizationClosed,
        
        /// <remarks/>
        _vendorReturnAuthorizationCredited,
        
        /// <remarks/>
        _vendorReturnAuthorizationPartiallyReturned,
        
        /// <remarks/>
        _vendorReturnAuthorizationPendingApproval,
        
        /// <remarks/>
        _vendorReturnAuthorizationPendingCredit,
        
        /// <remarks/>
        _vendorReturnAuthorizationPendingCreditPartiallyReturned,
        
        /// <remarks/>
        _vendorReturnAuthorizationPendingReturn,
        
        /// <remarks/>
        _workOrderBuilt,
        
        /// <remarks/>
        _workOrderCancelled,
        
        /// <remarks/>
        _workOrderClosed,
        
        /// <remarks/>
        _workOrderPartiallyBuilt,
        
        /// <remarks/>
        _workOrderPendingBuild,
        
        /// <remarks/>
        _workOrderPlanned,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:types.relationships_2015_1.lists.webservices.netsuite.com")]
    [System.Xml.Serialization.XmlRootAttribute("celigoContactType", Namespace="urn:types.missing_2015_1.transactions.webservices.netsuite.com", IsNullable=false)]
    public enum ContactType {
        
        /// <remarks/>
        _customer,
        
        /// <remarks/>
        _employee,
        
        /// <remarks/>
        _otherName,
        
        /// <remarks/>
        _partner,
        
        /// <remarks/>
        _vendor,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:types.common_2015_1.platform.webservices.netsuite.com")]
    [System.Xml.Serialization.XmlRootAttribute("celigoPermLevel", Namespace="urn:types.missing_2015_1.transactions.webservices.netsuite.com", IsNullable=false)]
    public enum PermissionLevel {
        
        /// <remarks/>
        _create,
        
        /// <remarks/>
        _edit,
        
        /// <remarks/>
        _full,
        
        /// <remarks/>
        _none,
        
        /// <remarks/>
        _view,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:types.common_2015_1.platform.webservices.netsuite.com")]
    [System.Xml.Serialization.XmlRootAttribute("celigoPermCode", Namespace="urn:types.missing_2015_1.transactions.webservices.netsuite.com", IsNullable=false)]
    public enum PermissionCode {
        
        /// <remarks/>
        _accessPaymentAuditLog,
        
        /// <remarks/>
        _accessTokenManagement,
        
        /// <remarks/>
        _accountDetail,
        
        /// <remarks/>
        _accounting,
        
        /// <remarks/>
        _accountingBook,
        
        /// <remarks/>
        _accountingLists,
        
        /// <remarks/>
        _accounts,
        
        /// <remarks/>
        _accountsPayable,
        
        /// <remarks/>
        _accountsPayableGraphing,
        
        /// <remarks/>
        _accountsPayableRegister,
        
        /// <remarks/>
        _accountsReceivable,
        
        /// <remarks/>
        _accountsReceivableGraphing,
        
        /// <remarks/>
        _accountsReceivableRegister,
        
        /// <remarks/>
        _accountsReceivableUnbilled,
        
        /// <remarks/>
        _adjustInventory,
        
        /// <remarks/>
        _adjustInventoryWorksheet,
        
        /// <remarks/>
        _admindocs,
        
        /// <remarks/>
        _adpImportData,
        
        /// <remarks/>
        _adpSetup,
        
        /// <remarks/>
        _advancedAnalytics,
        
        /// <remarks/>
        _advancedPDFHTMLTemplates,
        
        /// <remarks/>
        _allocationSchedules,
        
        /// <remarks/>
        _allowNonGLChanges,
        
        /// <remarks/>
        _allowPendingBookJournalEntry,
        
        /// <remarks/>
        _amendW4,
        
        /// <remarks/>
        _amortizationReports,
        
        /// <remarks/>
        _amortizationSchedules,
        
        /// <remarks/>
        _appDefinitionsAndPackages,
        
        /// <remarks/>
        _applicationPublishers,
        
        /// <remarks/>
        _approveDirectDeposit,
        
        /// <remarks/>
        _approveEFT,
        
        /// <remarks/>
        _approveOnlineBillPayments,
        
        /// <remarks/>
        _approveVendorPayments,
        
        /// <remarks/>
        _auditTrail,
        
        /// <remarks/>
        _backupYourData,
        
        /// <remarks/>
        _balanceSheet,
        
        /// <remarks/>
        _bankAccountRegisters,
        
        /// <remarks/>
        _billingInformation,
        
        /// <remarks/>
        _billingSchedules,
        
        /// <remarks/>
        _billOfDistribution,
        
        /// <remarks/>
        _billOfMaterialsInquiry,
        
        /// <remarks/>
        _billPurchaseOrders,
        
        /// <remarks/>
        _bills,
        
        /// <remarks/>
        _billSalesOrders,
        
        /// <remarks/>
        _bins,
        
        /// <remarks/>
        _binTransfer,
        
        /// <remarks/>
        _binWorksheet,
        
        /// <remarks/>
        _blanketPurchaseOrder,
        
        /// <remarks/>
        _blanketPurchaseOrderApproval,
        
        /// <remarks/>
        _budget,
        
        /// <remarks/>
        _buildAssemblies,
        
        /// <remarks/>
        _buildWorkOrders,
        
        /// <remarks/>
        _calculateTime,
        
        /// <remarks/>
        _calendar,
        
        /// <remarks/>
        _campaignHistory,
        
        /// <remarks/>
        _cases,
        
        /// <remarks/>
        _cashFlowStatement,
        
        /// <remarks/>
        _cashSale,
        
        /// <remarks/>
        _cashSaleRefund,
        
        /// <remarks/>
        _changeEmailOrPassword,
        
        /// <remarks/>
        _changeRole,
        
        /// <remarks/>
        _chargeRule,
        
        /// <remarks/>
        _chargeRunRules,
        
        /// <remarks/>
        _check,
        
        /// <remarks/>
        _checkItemAvailability,
        
        /// <remarks/>
        _classes,
        
        /// <remarks/>
        _classSegmentMapping,
        
        /// <remarks/>
        _closeAccount,
        
        /// <remarks/>
        _closeWorkOrders,
        
        /// <remarks/>
        _colorThemes,
        
        /// <remarks/>
        _commissionFeatureSetup,
        
        /// <remarks/>
        _commissionReports,
        
        /// <remarks/>
        _commitOrders,
        
        /// <remarks/>
        _commitPayroll,
        
        /// <remarks/>
        _companies,
        
        /// <remarks/>
        _companyInformation,
        
        /// <remarks/>
        _companyPreferences,
        
        /// <remarks/>
        _competitors,
        
        /// <remarks/>
        _componentWhereUsed,
        
        /// <remarks/>
        _contactRoles,
        
        /// <remarks/>
        _contacts,
        
        /// <remarks/>
        _convertClassesToDepartments,
        
        /// <remarks/>
        _convertClassesToLocations,
        
        /// <remarks/>
        _copyBudgets,
        
        /// <remarks/>
        _copyChartOfAccountsToNewCompany,
        
        /// <remarks/>
        _copyProjectTasks,
        
        /// <remarks/>
        _costedBillOfMaterialsInquiry,
        
        /// <remarks/>
        _costOfGoodsSoldRegisters,
        
        /// <remarks/>
        _countInventory,
        
        /// <remarks/>
        _createAllocationSchedules,
        
        /// <remarks/>
        _createConsolidationCompany,
        
        /// <remarks/>
        _createFiscalCalendar,
        
        /// <remarks/>
        _createInventoryCounts,
        
        /// <remarks/>
        _creditCard,
        
        /// <remarks/>
        _creditCardProcessing,
        
        /// <remarks/>
        _creditCardRefund,
        
        /// <remarks/>
        _creditCardRegisters,
        
        /// <remarks/>
        _creditMemo,
        
        /// <remarks/>
        _creditReturns,
        
        /// <remarks/>
        _crmGroups,
        
        /// <remarks/>
        _crmLists,
        
        /// <remarks/>
        _currency,
        
        /// <remarks/>
        _currencyAdjustmentJournal,
        
        /// <remarks/>
        _currencyRevaluation,
        
        /// <remarks/>
        _customAddressForm,
        
        /// <remarks/>
        _customBodyFields,
        
        /// <remarks/>
        _customCenterCategories,
        
        /// <remarks/>
        _customCenterLinks,
        
        /// <remarks/>
        _customCenters,
        
        /// <remarks/>
        _customCenterTabs,
        
        /// <remarks/>
        _customColumnFields,
        
        /// <remarks/>
        _customEntityFields,
        
        /// <remarks/>
        _customEntryForms,
        
        /// <remarks/>
        _customerCharge,
        
        /// <remarks/>
        _customerDeposit,
        
        /// <remarks/>
        _customerPayment,
        
        /// <remarks/>
        _customerProfile,
        
        /// <remarks/>
        _customerRefund,
        
        /// <remarks/>
        _customers,
        
        /// <remarks/>
        _customerStatus,
        
        /// <remarks/>
        _customEventFields,
        
        /// <remarks/>
        _customFields,
        
        /// <remarks/>
        _customHTMLLayouts,
        
        /// <remarks/>
        _customItemFields,
        
        /// <remarks/>
        _customItemNumberFields,
        
        /// <remarks/>
        _customizePage,
        
        /// <remarks/>
        _customLists,
        
        /// <remarks/>
        _customPDFLayouts,
        
        /// <remarks/>
        _customRecordEntries,
        
        /// <remarks/>
        _customRecordTypes,
        
        /// <remarks/>
        _customSublists,
        
        /// <remarks/>
        _customSubtabs,
        
        /// <remarks/>
        _customTransactionFields,
        
        /// <remarks/>
        _customTransactionForms,
        
        /// <remarks/>
        _customTransactionTypes,
        
        /// <remarks/>
        _deferredExpenseRegisters,
        
        /// <remarks/>
        _deferredRevenueRegisters,
        
        /// <remarks/>
        _deleteAllData,
        
        /// <remarks/>
        _deletedRecords,
        
        /// <remarks/>
        _deleteEvent,
        
        /// <remarks/>
        _departments,
        
        /// <remarks/>
        _departmentSegmentMapping,
        
        /// <remarks/>
        _deposit,
        
        /// <remarks/>
        _depositApplication,
        
        /// <remarks/>
        _directDepositStatus,
        
        /// <remarks/>
        _distributeInventory,
        
        /// <remarks/>
        _distributionNetwork,
        
        /// <remarks/>
        _documentsAndFiles,
        
        /// <remarks/>
        _duplicateCaseManagement,
        
        /// <remarks/>
        _duplicateDetectionSetup,
        
        /// <remarks/>
        _duplicateRecordManagement,
        
        /// <remarks/>
        _ebayExportImport,
        
        /// <remarks/>
        _editForecast,
        
        /// <remarks/>
        _editManagerForecast,
        
        /// <remarks/>
        _editProfile,
        
        /// <remarks/>
        _eftStatus,
        
        /// <remarks/>
        _emailReports,
        
        /// <remarks/>
        _emailTemplate,
        
        /// <remarks/>
        _employeeCommissionSchedulesPlans,
        
        /// <remarks/>
        _employeeCommissionTransaction,
        
        /// <remarks/>
        _employeeCommissionTransactionApproval,
        
        /// <remarks/>
        _employeeReminders,
        
        /// <remarks/>
        _employees,
        
        /// <remarks/>
        _employeeSocialSecurityNumbers,
        
        /// <remarks/>
        _enableFeatures,
        
        /// <remarks/>
        _enterCompletions,
        
        /// <remarks/>
        _enterOpeningBalances,
        
        /// <remarks/>
        _enterVendorCredits,
        
        /// <remarks/>
        _enterYearToDatePayrollAdjustments,
        
        /// <remarks/>
        _entityAccountMapping,
        
        /// <remarks/>
        _equityRegisters,
        
        /// <remarks/>
        _escalationAssignment,
        
        /// <remarks/>
        _escalationAssignmentRule,
        
        /// <remarks/>
        _establishQuotas,
        
        /// <remarks/>
        _estimate,
        
        /// <remarks/>
        _events,
        
        /// <remarks/>
        _expenseCategories,
        
        /// <remarks/>
        _expenseRegisters,
        
        /// <remarks/>
        _expenseReport,
        
        /// <remarks/>
        _expenses,
        
        /// <remarks/>
        _exportAsIIF,
        
        /// <remarks/>
        _exportLists,
        
        /// <remarks/>
        _faxMessages,
        
        /// <remarks/>
        _faxTemplate,
        
        /// <remarks/>
        _features,
        
        /// <remarks/>
        _financeCharge,
        
        /// <remarks/>
        _financeChargePreferences,
        
        /// <remarks/>
        _financialHistory,
        
        /// <remarks/>
        _financialStatementLayouts,
        
        /// <remarks/>
        _financialStatements,
        
        /// <remarks/>
        _financialStatementSections,
        
        /// <remarks/>
        _findMatchingOnlineBankingTransactions,
        
        /// <remarks/>
        _findTransaction,
        
        /// <remarks/>
        _fiscalCalendars,
        
        /// <remarks/>
        _fixedAssetRegisters,
        
        /// <remarks/>
        _form1099FederalMiscellaneousIncome,
        
        /// <remarks/>
        _form940EmployersAnnualFederalUnemploymentTaxReturn,
        
        /// <remarks/>
        _form941EmployersQuarterlyFederalTaxReturn,
        
        /// <remarks/>
        _formW2WageAndTaxStatement,
        
        /// <remarks/>
        _formW4EmployeesWithholdingAllowanceCertificate,
        
        /// <remarks/>
        _fulfillOrders,
        
        /// <remarks/>
        _generalLedger,
        
        /// <remarks/>
        _generatePriceLists,
        
        /// <remarks/>
        _generateRevenueCommitment,
        
        /// <remarks/>
        _generateRevenueCommitmentReversals,
        
        /// <remarks/>
        _generateSingleOrderRevenueContracts,
        
        /// <remarks/>
        _generateStatements,
        
        /// <remarks/>
        _genericAdminPermission,
        
        /// <remarks/>
        _genericResources,
        
        /// <remarks/>
        _globalAccountMapping,
        
        /// <remarks/>
        _grantingAccessToReports,
        
        /// <remarks/>
        _gstSummaryReport,
        
        /// <remarks/>
        _importCSVFile,
        
        /// <remarks/>
        _importOnlineBankingQIFFile,
        
        /// <remarks/>
        _importQuickenQIFFile,
        
        /// <remarks/>
        _importStateSalesTax,
        
        /// <remarks/>
        _income,
        
        /// <remarks/>
        _incomeRegisters,
        
        /// <remarks/>
        _incomeStatement,
        
        /// <remarks/>
        _individualPaycheck,
        
        /// <remarks/>
        _integration,
        
        /// <remarks/>
        _intercompanyAdjustments,
        
        /// <remarks/>
        _internalPublisher,
        
        /// <remarks/>
        _inventory,
        
        /// <remarks/>
        _inventoryCostTemplate,
        
        /// <remarks/>
        _invoice,
        
        /// <remarks/>
        _invoiceApproval,
        
        /// <remarks/>
        _issueComponents,
        
        /// <remarks/>
        _issueReports,
        
        /// <remarks/>
        _issues,
        
        /// <remarks/>
        _issueSetup,
        
        /// <remarks/>
        _itemAccountMapping,
        
        /// <remarks/>
        _itemCategoryLayouts,
        
        /// <remarks/>
        _itemDemandPlan,
        
        /// <remarks/>
        _itemFulfillment,
        
        /// <remarks/>
        _itemReceipt,
        
        /// <remarks/>
        _itemRevisions,
        
        /// <remarks/>
        _items,
        
        /// <remarks/>
        _itemSupplyPlan,
        
        /// <remarks/>
        _itemTemplates,
        
        /// <remarks/>
        _jobs,
        
        /// <remarks/>
        _journalApproval,
        
        /// <remarks/>
        _knowledgeBase,
        
        /// <remarks/>
        _kpiScorecards,
        
        /// <remarks/>
        _leadConversion,
        
        /// <remarks/>
        _leadConversionMapping,
        
        /// <remarks/>
        _leadSnapshotReminders,
        
        /// <remarks/>
        _letterMessages,
        
        /// <remarks/>
        _letterTemplate,
        
        /// <remarks/>
        _loadSampleData,
        
        /// <remarks/>
        _locations,
        
        /// <remarks/>
        _locationSegmentMapping,
        
        /// <remarks/>
        _lockTransactions,
        
        /// <remarks/>
        _logInUsingAccessTokens,
        
        /// <remarks/>
        _longTermLiabilityRegisters,
        
        /// <remarks/>
        _mailMerge,
        
        /// <remarks/>
        _makeJournalEntry,
        
        /// <remarks/>
        _manageAccountingPeriods,
        
        /// <remarks/>
        _managePayroll,
        
        /// <remarks/>
        _manageRoles,
        
        /// <remarks/>
        _manageTaxReportingPeriods,
        
        /// <remarks/>
        _manageUsers,
        
        /// <remarks/>
        _manufacturingCostTemplate,
        
        /// <remarks/>
        _manufacturingRouting,
        
        /// <remarks/>
        _marketingCampaignReports,
        
        /// <remarks/>
        _marketingCampaigns,
        
        /// <remarks/>
        _marketingTemplate,
        
        /// <remarks/>
        _markIssueAsShowStopper,
        
        /// <remarks/>
        _markWorkOrdersBuilt,
        
        /// <remarks/>
        _markWorkOrdersFirmed,
        
        /// <remarks/>
        _markWorkOrdersReleased,
        
        /// <remarks/>
        _massUpdates,
        
        /// <remarks/>
        _mediaFolders,
        
        /// <remarks/>
        _memorizedTransactions,
        
        /// <remarks/>
        _mobileDeviceAccess,
        
        /// <remarks/>
        _netWorth,
        
        /// <remarks/>
        _nonPostingRegisters,
        
        /// <remarks/>
        _noPermissionNecessary,
        
        /// <remarks/>
        _notesTab,
        
        /// <remarks/>
        _offlineClient,
        
        /// <remarks/>
        _onlineBankingStatement,
        
        /// <remarks/>
        _onlineCaseForm,
        
        /// <remarks/>
        _onlineCustomerForm,
        
        /// <remarks/>
        _onlineCustomRecordForm,
        
        /// <remarks/>
        _openidSingleSignOn,
        
        /// <remarks/>
        _opportunity,
        
        /// <remarks/>
        _otherAssetRegisters,
        
        /// <remarks/>
        _otherCurrentAssetRegisters,
        
        /// <remarks/>
        _otherCurrentLiabilityRegisters,
        
        /// <remarks/>
        _otherCustomFields,
        
        /// <remarks/>
        _otherExpenseRegisters,
        
        /// <remarks/>
        _otherIncomeRegisters,
        
        /// <remarks/>
        _otherLists,
        
        /// <remarks/>
        _otherNames,
        
        /// <remarks/>
        _outlookIntegration,
        
        /// <remarks/>
        _outlookIntegration3,
        
        /// <remarks/>
        _overrideEstimatedCostOnTransactions,
        
        /// <remarks/>
        _overridePaymentHold,
        
        /// <remarks/>
        _overridePeriodRestrictions,
        
        /// <remarks/>
        _partnerAuthorizedCommissionReports,
        
        /// <remarks/>
        _partnerCommissionReports,
        
        /// <remarks/>
        _partnerCommissionSchedulesPlans,
        
        /// <remarks/>
        _partnerCommissionTransaction,
        
        /// <remarks/>
        _partnerCommissionTransactionApproval,
        
        /// <remarks/>
        _partnerContribution,
        
        /// <remarks/>
        _partnerMonitorResults,
        
        /// <remarks/>
        _partners,
        
        /// <remarks/>
        _payBills,
        
        /// <remarks/>
        _paycheckJournal,
        
        /// <remarks/>
        _paychecks,
        
        /// <remarks/>
        _paymentMethods,
        
        /// <remarks/>
        _payrollCheckRegister,
        
        /// <remarks/>
        _payrollHoursAndEarnings,
        
        /// <remarks/>
        _payrollItems,
        
        /// <remarks/>
        _payrollJournalReport,
        
        /// <remarks/>
        _payrollLiabilityPayments,
        
        /// <remarks/>
        _payrollLiabilityReport,
        
        /// <remarks/>
        _payrollStateWithholding,
        
        /// <remarks/>
        _payrollSummaryAndDetailReports,
        
        /// <remarks/>
        _paySalesTax,
        
        /// <remarks/>
        _payTaxLiability,
        
        /// <remarks/>
        _pdfMessages,
        
        /// <remarks/>
        _pdfTemplate,
        
        /// <remarks/>
        _performSearch,
        
        /// <remarks/>
        _persistSearch,
        
        /// <remarks/>
        _phasedProcesses,
        
        /// <remarks/>
        _phoneCalls,
        
        /// <remarks/>
        _plannedStandardCost,
        
        /// <remarks/>
        _positions,
        
        /// <remarks/>
        _postingPeriodOnTransactions,
        
        /// <remarks/>
        _postTime,
        
        /// <remarks/>
        _postVendorBillVariances,
        
        /// <remarks/>
        _presentationCategories,
        
        /// <remarks/>
        _printChecksAndForms,
        
        /// <remarks/>
        _printEmailFax,
        
        /// <remarks/>
        _printShipmentDocuments,
        
        /// <remarks/>
        _processGSTRefund,
        
        /// <remarks/>
        _processPayroll,
        
        /// <remarks/>
        _projectProjectTemplateConversion,
        
        /// <remarks/>
        _projectTasks,
        
        /// <remarks/>
        _projectTemplates,
        
        /// <remarks/>
        _promotionCode,
        
        /// <remarks/>
        _provisioning,
        
        /// <remarks/>
        _provisioningForQa,
        
        /// <remarks/>
        _provisionTestDrive,
        
        /// <remarks/>
        _pstSummaryReport,
        
        /// <remarks/>
        _publicTemplateCategories,
        
        /// <remarks/>
        _publishDashboards,
        
        /// <remarks/>
        _publishEmployeeList,
        
        /// <remarks/>
        _publisherApplications,
        
        /// <remarks/>
        _publisherId,
        
        /// <remarks/>
        _publishForms,
        
        /// <remarks/>
        _publishKnowledgeBase,
        
        /// <remarks/>
        _publishRSSFeeds,
        
        /// <remarks/>
        _publishSearch,
        
        /// <remarks/>
        _purchaseContract,
        
        /// <remarks/>
        _purchaseContractApproval,
        
        /// <remarks/>
        _purchaseOrder,
        
        /// <remarks/>
        _purchaseOrderReports,
        
        /// <remarks/>
        _purchases,
        
        /// <remarks/>
        _quantityPricingSchedules,
        
        /// <remarks/>
        _quotaReports,
        
        /// <remarks/>
        _receiveOrder,
        
        /// <remarks/>
        _receiveReturns,
        
        /// <remarks/>
        _recognizeGiftCertificateIncome,
        
        /// <remarks/>
        _reconcile,
        
        /// <remarks/>
        _reconcileReporting,
        
        /// <remarks/>
        _recordCustomField,
        
        /// <remarks/>
        _refundReturns,
        
        /// <remarks/>
        _relatedItems,
        
        /// <remarks/>
        _reportCustomization,
        
        /// <remarks/>
        _reportScheduling,
        
        /// <remarks/>
        _requestForQuote,
        
        /// <remarks/>
        _requisition,
        
        /// <remarks/>
        _requisitionApproval,
        
        /// <remarks/>
        _resource,
        
        /// <remarks/>
        _resourceAllocationApproval,
        
        /// <remarks/>
        _resourceAllocationReports,
        
        /// <remarks/>
        _resourceAllocations,
        
        /// <remarks/>
        _returnAuthApproval,
        
        /// <remarks/>
        _returnAuthorization,
        
        /// <remarks/>
        _returnAuthorizationReports,
        
        /// <remarks/>
        _revalueInventoryCost,
        
        /// <remarks/>
        _revenueCommitment,
        
        /// <remarks/>
        _revenueCommitmentReversal,
        
        /// <remarks/>
        _revenueContracts,
        
        /// <remarks/>
        _revenueManagementVSOE,
        
        /// <remarks/>
        _revenueRecognitionReports,
        
        /// <remarks/>
        _revenueRecognitionSchedules,
        
        /// <remarks/>
        _roles,
        
        /// <remarks/>
        _runPayroll,
        
        /// <remarks/>
        _sales,
        
        /// <remarks/>
        _salesByPartner,
        
        /// <remarks/>
        _salesByPromotionCode,
        
        /// <remarks/>
        _salesCampaigns,
        
        /// <remarks/>
        _salesForceAutomation,
        
        /// <remarks/>
        _salesForceAutomationSetup,
        
        /// <remarks/>
        _salesOrder,
        
        /// <remarks/>
        _salesOrderApproval,
        
        /// <remarks/>
        _salesOrderFulfillmentReports,
        
        /// <remarks/>
        _salesOrderReports,
        
        /// <remarks/>
        _salesOrderTransactionReport,
        
        /// <remarks/>
        _salesRoles,
        
        /// <remarks/>
        _salesTerritory,
        
        /// <remarks/>
        _salesTerritoryRule,
        
        /// <remarks/>
        _samlSingleSignOn,
        
        /// <remarks/>
        _scheduleMassUpdates,
        
        /// <remarks/>
        _setUpAccounting,
        
        /// <remarks/>
        _setUpAchProcessing,
        
        /// <remarks/>
        _setUpAdpPayroll,
        
        /// <remarks/>
        _setUpBillPay,
        
        /// <remarks/>
        _setUpBudgets,
        
        /// <remarks/>
        _setUpCampaignEmailAddresses,
        
        /// <remarks/>
        _setupCampaigns,
        
        /// <remarks/>
        _setUpCompany,
        
        /// <remarks/>
        _setUpCsvPreferences,
        
        /// <remarks/>
        _setUpDomains,
        
        /// <remarks/>
        _setUpEbay,
        
        /// <remarks/>
        _setUpImageResizing,
        
        /// <remarks/>
        _setUpOpenidSingleSignOn,
        
        /// <remarks/>
        _setUpPartnerMonitor,
        
        /// <remarks/>
        _setUpPayroll,
        
        /// <remarks/>
        _setUpReminders,
        
        /// <remarks/>
        _setUpSamlSingleSignOn,
        
        /// <remarks/>
        _setUpSnapshots,
        
        /// <remarks/>
        _setUpSynchronization,
        
        /// <remarks/>
        _setUpWebServices,
        
        /// <remarks/>
        _setUpWebSite,
        
        /// <remarks/>
        _setUpYearStatus,
        
        /// <remarks/>
        _shippingItems,
        
        /// <remarks/>
        _shippingPartnerPackage,
        
        /// <remarks/>
        _shippingPartnerRegistration,
        
        /// <remarks/>
        _shippingPartnerShipment,
        
        /// <remarks/>
        _shortcuts,
        
        /// <remarks/>
        _standardCostVersion,
        
        /// <remarks/>
        _statementCharge,
        
        /// <remarks/>
        _statisticalAccountRegisters,
        
        /// <remarks/>
        _storeCategories,
        
        /// <remarks/>
        _storeContentCategories,
        
        /// <remarks/>
        _storeContentItems,
        
        /// <remarks/>
        _storeLogoUpload,
        
        /// <remarks/>
        _storeTabs,
        
        /// <remarks/>
        _subsidiaries,
        
        /// <remarks/>
        _suiteAppInstallation,
        
        /// <remarks/>
        _suiteBundler,
        
        /// <remarks/>
        _suiteBundlerUpgrades,
        
        /// <remarks/>
        _suiteScript,
        
        /// <remarks/>
        _suiteSignon,
        
        /// <remarks/>
        _support,
        
        /// <remarks/>
        _supportCaseIssue,
        
        /// <remarks/>
        _supportCaseOrigin,
        
        /// <remarks/>
        _supportCasePriority,
        
        /// <remarks/>
        _supportCaseSnapshotReminders,
        
        /// <remarks/>
        _supportCaseStatus,
        
        /// <remarks/>
        _supportCaseTerritory,
        
        /// <remarks/>
        _supportCaseTerritoryRule,
        
        /// <remarks/>
        _supportCaseType,
        
        /// <remarks/>
        _supportSetup,
        
        /// <remarks/>
        _swapPricesBetweenPriceLevels,
        
        /// <remarks/>
        _systemEmailTemplate,
        
        /// <remarks/>
        _systemStatus,
        
        /// <remarks/>
        _tasks,
        
        /// <remarks/>
        _tax,
        
        /// <remarks/>
        _taxItems,
        
        /// <remarks/>
        _taxSchedules,
        
        /// <remarks/>
        _teamSellingContribution,
        
        /// <remarks/>
        _tegataAccounts,
        
        /// <remarks/>
        _tegataPayable,
        
        /// <remarks/>
        _tegataReceivable,
        
        /// <remarks/>
        _telephonyIntegration,
        
        /// <remarks/>
        _templateCategories,
        
        /// <remarks/>
        _terminationReasons,
        
        /// <remarks/>
        _testdriveMasters,
        
        /// <remarks/>
        _timer,
        
        /// <remarks/>
        _timeTracking,
        
        /// <remarks/>
        _trackMessages,
        
        /// <remarks/>
        _trackTime,
        
        /// <remarks/>
        _transactionDetail,
        
        /// <remarks/>
        _transactionNumberingAuditLog,
        
        /// <remarks/>
        _transferFunds,
        
        /// <remarks/>
        _transferInventory,
        
        /// <remarks/>
        _transferOrder,
        
        /// <remarks/>
        _transferOrderApproval,
        
        /// <remarks/>
        _translation,
        
        /// <remarks/>
        _trialBalance,
        
        /// <remarks/>
        _twoFactorAuthentication,
        
        /// <remarks/>
        _unbilledReceivableRegisters,
        
        /// <remarks/>
        _unbuildAssemblies,
        
        /// <remarks/>
        _uncategorizedPresentationItems,
        
        /// <remarks/>
        _units,
        
        /// <remarks/>
        _updatePrices,
        
        /// <remarks/>
        _upsellAssistant,
        
        /// <remarks/>
        _upsellSetup,
        
        /// <remarks/>
        _upsellWizard,
        
        /// <remarks/>
        _userAccessTokens,
        
        /// <remarks/>
        _userPreferences,
        
        /// <remarks/>
        _usersAndPasswords,
        
        /// <remarks/>
        _vendorBillApproval,
        
        /// <remarks/>
        _vendorPaymentStatus,
        
        /// <remarks/>
        _vendorRequestForQuote,
        
        /// <remarks/>
        _vendorReturnAuthApproval,
        
        /// <remarks/>
        _vendorReturnAuthorization,
        
        /// <remarks/>
        _vendorReturns,
        
        /// <remarks/>
        _vendors,
        
        /// <remarks/>
        _viewLoginAuditTrail,
        
        /// <remarks/>
        _viewOnlineBillPayStatus,
        
        /// <remarks/>
        _viewPaymentEvents,
        
        /// <remarks/>
        _viewUnencryptedCreditCards,
        
        /// <remarks/>
        _webServices,
        
        /// <remarks/>
        _webSiteExternalPublisher,
        
        /// <remarks/>
        _webSiteManagement,
        
        /// <remarks/>
        _webSiteReport,
        
        /// <remarks/>
        _webStoreEmailTemplate,
        
        /// <remarks/>
        _webStoreReport,
        
        /// <remarks/>
        _workCalendar,
        
        /// <remarks/>
        _workflow,
        
        /// <remarks/>
        _workOrder,
        
        /// <remarks/>
        _workOrderClose,
        
        /// <remarks/>
        _workOrderCompletion,
        
        /// <remarks/>
        _workOrderIssue,
        
        /// <remarks/>
        _workplaces,
    }
}
