 
//~ Generated by NetSuiteServiceManagerTemplate.tt
#pragma warning disable 1591
using System;
using com.celigo.net.ServiceManager.SuiteTalk;

namespace com.celigo.net.ServiceManager
{
	public partial class NetSuiteServiceManager
	{
#if !FIRSTBUILD
        public override WriteResponse[] AddList(Record[] records)
        {
            if (records == null || records.Length == 0)
                return new WriteResponse[0];
            return ProcessRecordInBatchMode(records, "addList");
        }
        public override WriteResponse[] DeleteList(BaseRef[] baseRefs)
        {
            if (baseRefs == null || baseRefs.Length == 0)
                return new WriteResponse[0];
			return ProcessRecordDeletesInBatchMode(baseRefs, "deleteList");
        }
        public override WriteResponse[] UpdateList(Record[] records)
        {
            if (records == null || records.Length == 0)
                return new WriteResponse[0];
            return ProcessRecordInBatchMode(records, "updateList");
        }
        public override WriteResponse[] UpsertList(Record[] records)
        {
            if (records == null || records.Length == 0)
                return new WriteResponse[0];
            return ProcessRecordInBatchMode(records, "upsertList");
        }
#endif
	}
}
